version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "trek-db"
      POSTGRES_USER: "adirontech"
      POSTGRES_PASSWORD: ${DB_PASSWORD}