DROP TABLE IF EXISTS UserSessions CASCADE;

CREATE TABLE UserSessions (
  id SERIAL PRIMARY KEY,
  session_key VARCHAR (100) NOT NULL,
  user_id INT NOT NULL,
  exp_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + interval '4 hours',
  FOREIGN KEY (user_iD) REFERENCES Users (id)
);