INSERT INTO WildernessAreas (id, name)
VALUES
(1, 'High Peaks'),
(2, 'AMR'),
(3, 'Five Ponds')

INSERT INTO POIs (id, name, type, wilderness_area)
VALUES 
    (1, 'Heart Lake', 'Trailhead', 1),
    (2, 'The Garden', 'Trailhead', 1),
    (3, 'Upper Works', 'Trailhead', 1),
    (4, 'Elk Lake', 'Trailhead', 1),
    (5, 'Coreys', 'Trailhead', 1),
    (6, 'Mt. Marcy', 'Peak', 1),
    (7, 'Haystack', 'Peak', 1),
    (8, 'Gray', 'Peak', 1),
    (9, 'Algonquin', 'Peak', 1),
    (10, 'Dix', 'Peak', 1),
    (11, 'Grace', 'Peak', 1),
    (12, 'South Dix', 'Peak', 1),
    (13, 'Hough', 'Peak', 1),
    (14, 'Macomb', 'Peak', 1),
    (15, 'Skylight', 'Peak', 1),
    (16, 'Allen', 'Peak', 1),
    (17, 'Redfield', 'Peak', 1),
    (18, 'Cliff', 'Peak', 1),
    (19, 'Santanoni', 'Peak', 1),
    (20, 'Panther', 'Peak', 1),
    (21, 'Couchsachraga', 'Peak', 1),
    (22, 'Seymour', 'Peak', 1),
    (23, 'Seward', 'Peak', 1),
    (24, 'Donaldson', 'Peak', 1),
    (25, 'Emmons', 'Peak', 1),
    (26, 'Sawteeth', 'Peak', 1),
    (27, 'Basin', 'Peak', 1),
    (28, 'Saddleback', 'Peak', 1),
    (29, 'Gothics', 'Peak', 1),
    (30, 'Armstrong', 'Peak', 1),
    (31, 'Upper Wolf Jaw', 'Peak', 1),
    (32, 'Lower Wolf Jaw', 'Peak', 1),
    (33, 'Big Slide', 'Peak', 1),
    (34, 'Phelps', 'Peak', 1),
    (35, 'TableTop', 'Peak', 1),
    (36, 'Nye', 'Peak', 1),
    (36, 'Street', 'Peak', 1),
    (37, 'Colden', 'Peak', 1),
    (38, 'Avalanche Lake', 'Scenic', 1),
    (39, 'Marcy Dam', 'Scenic', 1),
    (40, 'Indian Falls', 'Scenic', 1),
    (41, 'Johns Brook Lodge', 'Lodge', 1),
    (42, 'Nippletop', 'Peak', 2),
    (43, 'Dial', 'Peak', 2),
    (44, 'Colvin', 'Peak', 2),
    (45, 'Blake', 'Peak', 2),
    (46, 'Big Shallow Pond', 'Leanto', 3),
    (47, 'Little Shallow Pond', 'Leanto', 3),
    (48, 'High Falls', 'Trailhead', 3),
    (49, 'Dead Creek', 'Trailhead', 3),
    (50, 'Cat Mountain', 'Peak', 3)