INSERT INTO POIs (id, name, type, wilderness_area)
VALUES 
    (1, 'Heart Lake', 'Trailhead', 'High Peaks'),
    (2, 'The Garden', 'Trailhead', 'High Peaks'),
    (3, 'Upper Works', 'Trailhead', 'High Peaks'),
    (4, 'Elk Lake', 'Trailhead', 'High Peaks'),
    (5, 'Coreys', 'Trailhead', 'High Peaks'),
    (6, 'Mt. Marcy', 'Peak', 'High Peaks'),
    (7, 'Haystack', 'Peak', 'High Peaks'),
    (8, 'Gray', 'Peak', 'High Peaks'),
    (9, 'Algonquin', 'Peak', 'High Peaks'),
    (10, 'Dix', 'Peak', 'High Peaks'),
    (11, 'Grace', 'Peak', 'High Peaks'),
    (12, 'South Dix', 'Peak', 'High Peaks'),
    (13, 'Hough', 'Peak', 'High Peaks'),
    (14, 'Macomb', 'Peak', 'High Peaks'),
    (15, 'Skylight', 'Peak', 'High Peaks'),
    (16, 'Allen', 'Peak', 'High Peaks'),
    (17, 'Redfield', 'Peak', 'High Peaks'),
    (18, 'Cliff', 'Peak', 'High Peaks'),
    (19, 'Santanoni', 'Peak', 'High Peaks'),
    (20, 'Panther', 'Peak', 'High Peaks'),
    (21, 'Couchsachraga', 'Peak', 'High Peaks'),
    (22, 'Seymour', 'Peak', 'High Peaks'),
    (23, 'Seward', 'Peak', 'High Peaks'),
    (24, 'Donaldson', 'Peak', 'High Peaks'),
    (25, 'Emmons', 'Peak', 'High Peaks'),
    (26, 'Sawteeth', 'Peak', 'High Peaks'),
    (27, 'Basin', 'Peak', 'High Peaks'),
    (28, 'Saddleback', 'Peak', 'High Peaks'),
    (29, 'Gothics', 'Peak', 'High Peaks'),
    (30, 'Armstrong', 'Peak', 'High Peaks'),
    (31, 'Upper Wolf Jaw', 'Peak', 'High Peaks'),
    (32, 'Lower Wolf Jaw', 'Peak', 'High Peaks'),
    (33, 'Big Slide', 'Peak', 'High Peaks'),
    (34, 'Phelps', 'Peak', 'High Peaks'),
    (35, 'TableTop', 'Peak', 'High Peaks'),
    (36, 'Nye', 'Peak', 'High Peaks'),
    (36, 'Street', 'Peak', 'High Peaks'),
    (37, 'Colden', 'Peak', 'High Peaks'),
    (38, 'Avalanche Lake', 'Scenic', 'High Peaks'),
    (39, 'Marcy Dam', 'Scenic', 'High Peaks'),
    (40, 'Indian Falls', 'Scenic', 'High Peaks'),
    (41, 'Johns Brook Lodge', 'Lodge', 'High Peaks'),
    (42, 'Nippletop', 'Peak', 'AMR'),
    (43, 'Dial', 'Peak', 'AMR'),
    (44, 'Colvin', 'Peak', 'AMR'),
    (45, 'Blake', 'Peak', 'AMR'),
    (46, 'Big Shallow Pond', 'Leanto', 'Five Ponds'),
    (47, 'Little Shallow Pond', 'Leanto', 'Five Ponds'),
    (48, 'High Falls', 'Trailhead', 'Five Ponds'),
    (49, 'Dead Creek', 'Trailhead', 'Five Ponds'),
    (50, 'Cat Mountain', 'Peak', 'Five Ponds')